Allow general user to update their own tuit
aliu19/fse-sp22-tuiter-client-react pull request #26
Opened 2022-04-20 17:12 UTC by averywpx

2022-04-21 03:48 UTC, aliu19 requested changes

2022-04-21 03:48 UTC, aliu19 commented on src/components/tuits/tuit.js
>                         className="fas fa-remove tuit-button fa-2x fa-pull-right"/>
Update to have the pencil, green checkmark, and red trash can as shown in main branch (may be fixed during selection during merge?)

2022-04-21 03:56 UTC, aliu19 approved these changes
Update to have the pencil, green checkmark, and red trash can in the tuit as shown in main branch, which should be fixed from resolving merge conflicts

2022-04-21 18:25 UTC, caijiah commented
The code looks fine, but I don't remember we want general users to edit tuits.

2022-04-21 18:40 UTC, caijiah commented on src/components/tuits/tuit.js
> +                    <i className='float-end fa fa-cog edit-button'
Need change to pen icon.

2022-04-21 18:40 UTC, caijiah commented on src/components/tuits/tuit.js
> +                        className="float-end fa fa-check"/>
You probably also need delete button here.

2022-04-21 18:45 UTC, caijiah requested changes
We have discussed in chat that we want only owner of the tuit can edit the tuit.

2022-04-26 19:02 UTC, caijiah approved these changes

2022-04-26 20:59 UTC, closed without merging